[tools]
"github:UpliftGames/wally" = "0.3.2"
"github:rojo-rbx/rojo" = "7.6.1"
"aqua:luau-lang/luau" = "0.703"
"github:scythe-technology/zune" = "0.5.1"

[tasks."dev:sourcemap"]
run = "rojo sourcemap demo.project.json -o sourcemap.json --watch"

[tasks."dev:syncer"]
run = "rojo serve demo.project.json"

[tasks."dev"]
depends = ["dev:sourcemap", "dev:syncer"]
